adminapp/urls.py
from django.urls import path
from . import views

app_name = 'adminapp'
urlpatterns = [
    path('', views.home, name="adminhome"),
    path('loginadmin/', views.loginAdmin, name="loginadmin"),
    path('logoutadmin/', views.logoutAdmin, name="logoutadmin"),

    path('college-student/<int:id>', views.fetchStudents, name="college-student"),
    path('all-students-data/', views.allStudents, name="all-students-data"),
    path('college-exam/<int:id>', views.fetchExams, name="college-exam"),
    path('exam/', views.exam, name="exam"),
    path('exam-info/<int:id>', views.examInfo, name="exam-info"),


    path('adminuser/', views.fetchAdmin, name="adminuser"),
    path('addcollege/', views.addCollege, name="addcollege"),
    path('addexam/', views.addExam, name="addexam"),
    path('addadmin/', views.addAdmin, name="addadmin"),
    path('addquestion/<int:id>', views.addQuestion, name="addquestion"),
    path('addoption/<int:id>', views.addOption, name="addoption"),
    path('edit-question/<int:exam_id>/<int:q_id>', views.editQuestion, name="edit-question"),
    path('studentrecords/<int:exam_id>/<int:college_id>', views.studentrecord, name="studentrecords"),
]

exam/urls.py
from django.urls import path
from . import views

app_name = 'exam'
urlpatterns = [
    path('', views.selectExam, name="select-exam"),
    path('home/<int:exam_id>', views.home, name='home'),
    path('signup/', views.register, name="signup"),
    path('signin/',views.signin, name="signin"),
    path('startexam/<int:id>', views.exam, name="startexam"),
    path('saveans/', views.saveans, name="saveans"),
    
    path('result/', views.result, name="result"),
    path('logout/', views.signout, name="logout"),
]

student_exam_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exam.urls', namespace='exam')),
    path('adminapp/', include('adminapp.urls' ,namespace="adminapp")),
]

exam/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save



# Create your models here.
class College(models.Model):
    clg_name = models.CharField(max_length=300)

    def __str__(self):
        return self.clg_name

class Exam(models.Model):
    exam_name = models.CharField(max_length=100)
    college = models.ForeignKey(College, on_delete=models.CASCADE, related_name='exam')

    def __str__(self):
        return self.exam_name


class Question(models.Model):
    CATEGORY = (
        ('Aptitude', 'Aptitude'),
        ('Programming', 'Programming')
    )
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='exam')
    question_text = models.TextField()
    category = models.CharField(max_length=30, choices=CATEGORY, default="None")
    answer = models.CharField(max_length=1, null=True, blank=True)

    def __str__(self):
        return self.question_text

class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='question')
    option_value1 = models.CharField(max_length=1, default="A")
    option_text1 = models.CharField(max_length = 300)
    option_value2 = models.CharField(max_length=1,default="B")
    option_text2 = models.CharField(max_length = 300)
    option_value3 = models.CharField(max_length=1,default="C")
    option_text3 = models.CharField(max_length = 300)
    option_value4 = models.CharField(max_length=1,default="D")
    option_text4 = models.CharField(max_length = 300)

    def __str__(self):
        return self.question.question_text + " : " + self.option_text1 + ":" + self.option_text2 + ":" + self.option_text3 + ":" + self.option_text4



class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    college = models.ForeignKey(College, on_delete=models.CASCADE, related_name='college')
    roll_no = models.CharField(max_length=15)




def student_profile(sender, created, instance, **kwargs):
    if created:
        if instance.is_superuser == True:
            group = Group.objects.get(name='admin')
            instance.groups.add(group)
            print("True Again")

        else:
            group = Group.objects.get(name='student')
            instance.groups.add(group)
            Student.objects.create(
                user = instance, 
                college = instance.college,
                roll_no = instance.roll_no
            )   
post_save.connect(student_profile, sender=User)



class Record(models.Model):
    student_id = models.CharField(max_length=10)
    exam_id = models.CharField(max_length=10)
    question_id = models.CharField(max_length=10)
    answer = models.CharField(max_length=1, default='N')

    def __str__(self):
        return self.question_id + " : "+self.answer + "----Student_ID : " + self.student_id

exam/forms.py
from .models import Student
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Exam



class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class StudentForm(ModelForm):

    class Meta:
        model = Student
        fields ='__all__'
        exclude = ['user']

class UserAuthentication(AuthenticationForm):
    class Meta:
        model = User
        fields = '__all__'

class ExamForm(ModelForm):
    class Meta:
        model : Exam
        fields : '__all__'
        exclude : 'college'

exam/views.py
from django.shortcuts import render, redirect, HttpResponsePermanentRedirect
from .models import College, Exam, Question, Option, Record
from django.core.paginator import Paginator
from .forms import CreateUserForm, StudentForm, UserAuthentication, ExamForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import allowed_users
from django.contrib import messages
from django.urls import reverse
import random


# Create your views here.
global question_list
global answer_list


def register(request):
    user_form = CreateUserForm()
    student_form = StudentForm()
    if request.method == "POST":
        user_form = CreateUserForm(request.POST)
        student_form = StudentForm(request.POST)
     
        if user_form.is_valid() and student_form.is_valid():
            try:
                username = user_form.cleaned_data['username']
                college = student_form.cleaned_data["college"]
                roll_no = student_form.cleaned_data.get("roll_no")
                user = user_form.save(commit=False)
                user.college = college
                user.roll_no = roll_no
                user.save()
                messages.success(request, f"{username} created successfully")
                return redirect(reverse('exam:signin'))
            except Exception as e:
                messages.warning(request, "Please Enter Valid/Unique(username, email)/Strong Data")

           
        else:
            messages.warning(request, "Please Enter Valid/Unique(username, email)/Strong Data")

    context ={'user_form':user_form,'student_form':student_form}
    return render(request, 'exam/register.html', context)

def signin(request):
    auth_form = UserAuthentication()
    if request.method == "POST":
        user = authenticate(request, username = request.POST['username'], password=request.POST['password'])
        if user:
            login(request, user)
            return redirect('/')
        else:
            messages.warning(request, "Invalid Credentials")

    context= {'auth_form':auth_form}
    return render(request, template_name='exam/signin.html', context = context)


@login_required
@allowed_users(allowed_roles=['student'])
def signout(request):
    logout(request)
    return redirect('/')

@login_required(login_url='exam:signin')
@allowed_users(allowed_roles=['student'])
def selectExam(request):
    exams = Exam.objects.filter(college = request.user.student.college.id)
    if request.method == "POST":
        exam = request.POST['exam']
        exam = Exam.objects.filter(exam_name=exam, college=request.user.student.college.id)
        return redirect(reverse('exam:home',kwargs={'exam_id' : exam[0].id}))
    context = {'exams':exams}
    return render(request, 'exam/select_college.html', context)


@login_required(login_url='exam:signin')
@allowed_users(allowed_roles=['student'])
def home(request, exam_id):
    question = Question.objects.filter(exam=exam_id)
    global answer_list
    answer_list = []
    global question_list
    question_list = list(question)
    for question in question_list:
        Record.objects.create(student_id=request.user.id, exam_id=exam_id, question_id=question.id)
    random.shuffle(question_list)
    return render(request, 'exam/home.html', {'exam_id':exam_id})

@login_required(login_url='exam:signin')
@allowed_users(allowed_roles=['student'])
def exam(request, id):
    global question_list
    exam_question = question_list[:]
    option_list = []
    for ques in exam_question:
        option = Option.objects.get(question=ques.id)
        option_list.append(option)

    context = {'questions': exam_question, 'questions_page': exam_question, 'option_list': option_list, 'exam_id':id}
    return render(request, 'exam/exam.html', context)

@login_required
def saveans(request):
    question_id = request.GET['qid']
    answer = request.GET['ans']
    exam_id = request.GET['eid']
    Record.objects.filter(question_id=question_id, exam_id=exam_id, student_id=request.user.id).update(answer=answer)
    

@login_required(login_url='exam:signin')
@allowed_users(allowed_roles=['student'])
def result(request):
    score = 0
    global question_list
    compare_list = question_list[:]
    for question in compare_list:
        record = Record.objects.get(question_id=question.id)

        if record.answer == question.answer:
            score += 2
    return render(request, 'exam/result.html', {'score':score})

exam/templates/exam/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    {% block style %} {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>

    {% block register %}

    {% endblock %}

    {% block login %}
    {% endblock %}


    {% block exam %}
    {% endblock %}


    {% block result %}
    {% endblock %}

    {% block script %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>

exam/templates/exam/exam.html
{% extends 'exam/base.html' %} {% block style %}
<style>
 
  .nav {
    height: 5rem;
    /* justify-content: center !important; */
  }

  .custom {
    font-size: 1.5rem;
  }
</style>
{% endblock %} {% block exam %}
<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light nav">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse text-center flexing" id="navbarNavDropdown">
    <ul class="navbar-nav text-center">
      <li class="nav-item mx-3 custom">Name: {{request.user}}</li>
      <li class="nav-item mx-3 custom">Email: {{request.user.email}}</li>
      <li class="nav-item mx-3 custom">
        College: {{request.user.student.college}}
      </li>
      <li class="nav-item mx-3 custom">Roll no.: {{request.user.student.roll_no}}</li>
      
      <li class="nav-item mx-3 custom">Timer :<span id="timer"></span></li>
    </ul>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-lg-10 col-md-8 border border-success p-4 m-2 mx-auto">
      {% if questions %}
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="aptitude-tab" data-toggle="tab" href="#aptitude" role="tab"
            aria-controls="aptitude" aria-selected="true">Aptitude</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link" id="programming-tab" data-toggle="tab" href="#programming" role="tab" aria-controls="programming"
            aria-selected="false">Programming</a>
        </li>
      </ul>
      <div class="mt-4"></div>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="aptitude" role="tabpanel" aria-labelledby="Aptitude"> 
            {% for question in questions_page %} 
                {% if question.category == 'Aptitude' %}
                <h5>Q {{exam_id}}-{{ question.question_text }}</h5>
                <br />
                    {% for option in option_list %} 
                        {% if option.question.id == question.id %}
                            <input type="radio" name="ans{{question.id}}" class="jk" value="A" />{{option.option_text1}}<br />
                            <input type="radio" name="ans{{question.id}}" value="B" />{{option.option_text2}}<br />
                            <input type="radio" name="ans{{question.id}}" value="C" />{{option.option_text3}}<br />
                            <input type="radio" name="ans{{question.id}}" value="D" />{{option.option_text4}}<br />
                            <button data-id="{{question.id}}" name="submit{{question.id}}" class="submitAnswer btn btn-sm btn-outline-info form-control">
                              Submit Answer
                            </button>
                        {% endif %}
                    {% endfor %}
                    <br />
                    <hr>
                    {% endif %} 
            {% endfor %}

        </div>
        <div class="tab-pane fade" id="programming" role="tabpanel" aria-labelledby="Programming">
          {% for question in questions_page %} 
          {% if question.category == 'Programming' %}
          <h5>Q-{{ question.question_text }}</h5>
          <br />
              {% for option in option_list %} 
                  {% if option.question.id == question.id %}
                      <input type="radio" name="ans{{question.id}}" value="A" />{{option.option_text1}}<br />
                      <input type="radio" name="ans{{question.id}}" value="B" />{{option.option_text2}}<br />
                      <input type="radio" name="ans{{question.id}}" value="C" />{{option.option_text3}}<br />
                      <input type="radio" name="ans{{question.id}}" value="D" />{{option.option_text4}}<br />
                      <button  data-id="{{question.id}}" name="submit{{question.id}}"  class="submitAnswer btn btn-sm btn-outline-info form-control">
                        Submit Answer
                      </button>
                      <div id="submitted"></div>
                  {% endif %}
              {% endfor %}
              <br />
              <hr>
              {% endif %} 
      {% endfor %}
                </div>
      </div>
      <div class="text-center">

        <a href="{% url 'exam:result' %}" class="btn btn-success">Submit Quiz</a>
      </div>
      {% else %}
      <h3>No Qustions</h3>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

{% block script %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script>
  var myTimer;
function clock() {
    myTimer = setInterval(myClock, 1000);
    var c = 3600; //Initially set to 1 hour


    function myClock() {
        --c
        var seconds = c % 60; // Seconds that cannot be written in minutes
        var secondsInMinutes = (c - seconds) / 60; // Gives the seconds that COULD be given in minutes
        var minutes = secondsInMinutes % 60; // Minutes that cannot be written in hours
        var hours = (secondsInMinutes - minutes) / 60;
        // Now in hours, minutes and seconds, you have the time you need.
        console.clear();
        console.log(hours + ":" + minutes + ":" + seconds)
        document.getElementById('timer').innerHTML = minutes + ":" + seconds
        if (c == 0) {
          clearInterval(myTimer);
          window.location.href = 'http://127.0.0.1:8000/result/'
        }
    }
}
clock();
</script>
<script>
  var saveAnsButton;

  $('.submitAnswer').on('click',function(){
    var id =$(this).data('id');
    var submitted = document.getElementById('submitted');
    var ans="Not Answered";
    if ($("input:radio[name=ans"+id+"]").is(":checked")){
      ans = $("input[name=ans"+id+"]:checked").val();
      $(this).prop('disabled',true);
      $(this).html('Answer Submited.....');

    }
    document.getElementById('submitted').innerHTML = 'Answer Submited'
    //var submitans = document.getElementById('')
    saveans(id,ans);
  });
   
  function saveans(qid,ans){   
      var req = new XMLHttpRequest();
      var url = '/saveans?qid=' + String(qid)+'&ans=' + String(ans) + "&eid=" + String('{{exam_id}}');
      req.open("GET", url, true);
      req.send();

  }
  
  
  </script>
{% endblock script%}

exam/templates/exam/home.html
{% extends 'exam/base.html' %}
{% block exam %}

<div class="jumbotron text-center">
    <h1 class="display-4">Welcome {{request.user}}</h1>
    <hr class="my-4">
    <p>Email :{{ request.user.email }}</p>
    <p>College :{{ request.user.student.college }}</p>
    <p>Roll No. :{{ request.user.student.roll_no }}</p>
    <p><b>Instruction</b></p>
    <p>1- Time Duration will be 60 minutes</p>
    <p>2- During Exam, Select one answer and click on "Submit Ans" to record answer and then click Next</p>
    <a class="btn btn-primary btn-lg" href="{% url 'exam:startexam' exam_id %}"  role="button">Start Exam</a>
  </div>
{% endblock %}

exam/templates/exam/register.html
{% extends 'exam/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Student SignUp {% endblock %}
{% block style %}
<style>
    body,
    html {
        margin: 0;
        padding: 0;
        height: 100%;
        background: #7abecc !important;
    }
    .user_card {
        width: 470px;
        margin-top: auto;
        margin-bottom: auto;
        background: #74cfbf;
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;

    }

    .form_container {
        margin-top: 20px;
        width: 100%;
    }

    #form-title{
        color: #fff;

    }
    .login_btn {
        width: 100%;
        background: #33ccff !important;
        color: white !important;
    }
    .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }
    .login_container {
        padding: 0 2rem;
    }

    #messages{
        background-color: grey;
        color: #fff;
        padding: 10px;
        margin-top: 10px;
    }
    #id_college{
        height: 2.4em;
    width: 100%;
    border-radius: 4px;
    }
    .form{
        min-width: 100%;
    }

</style>
{% endblock %}
{% block register %}
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">REGISTER ACCOUNT</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="" class="form">
                    {% csrf_token %}
                    {{ user_form.username.label_tag }}*
                    <div class="input-group mb-3">
                        {{ user_form.username }}
                        
                    </div>
                    <ul>
                        <li>Use Uppercase, Lowercase, Special Characters and Numbers</li>
                        <li>e.g. Smit_Patel_1998</li>
                    </ul>
                    {{ user_form.email.label_tag }}*
                    <div class="input-group mb-2">
                        {{ user_form.email }}
                    </div>
                    {{ user_form.password1.label_tag }}*
                    <div class="input-group mb-2">
                        {{ user_form.password1 }}
                    </div>
                    <ul>
                        <li>Use Uppercase, Lowercase, Special Characters and Numbers</li>
                        <li>e.g. SBV@portal1</li>
                    </ul>
                    {{ user_form.password2.label_tag }}*
                    <div class="input-group mb-2">
                        {{ user_form.password2 }}
                    </div>
                    {{ student_form.college.label_tag }}*
                    <div class="input-group mb-2 field">
                        {{ student_form.college }}
                    </div>
                    {{ student_form.roll_no.label_tag }}*
                    <div class="input-group mb-2">
                        {{ student_form.roll_no }}
                    </div>

                       <div class="d-flex justify-content-center mt-3 login_container">
                         <input class="btn login_btn" type="submit" value="Register Account">
                       </div>
                </form>
            </div>
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'exam:signin' %}" class="ml-2">Login</a>
                </div>
            </div>
            <div class="messeges">
                {% for message in messages %}
                   <p id=messages>{{message}}</p> 
                  
                {% endfor %}
            </div>
        </div>
        
    </div>
    
</div>
{% endblock %}
{% block script %}
<script>
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field 
*/

//Query All input fields
var form_fields = document.getElementsByTagName('input')
form_fields[1].placeholder='Username..Must be unique';
form_fields[2].placeholder='Email..';
form_fields[3].placeholder='Enter password...';
form_fields[4].placeholder='Re-enter Password...';
form_fields[5].placeholder='Roll Number';
//form_fields[6].placeholder='Roll Number';


for (var field in form_fields){	
form_fields[field].className += ' form-control'
}
</script>
{% endblock %}

exam/templates/exam/result.html
{% extends 'exam/base.html' %}

{% block style %}
<style>

    .green{
        background-color:rgba(90, 218, 90, 0.753) !important;
        
    }
    .red{
        background-color: rgba(238, 57, 57, 0.877) !important;
    }
</style>
{% endblock %}


{% block result %}
  

  
{% if score > 60 %}
<div class="jumbotron green text-center">
    <h1 class="display-4">{{ request.user }}</h1>
    <p class="lead">You have successfully passed the exam with score of <b>{{ score }}</b></p>
    <hr class="my-4">
    <a class="btn btn-primary btn-lg" href="{% url 'exam:logout' %}" role="button">Log Out</a>
</div>
    
{% else %}
<div class="jumbotron red text-center">
    <h1 class="display-4">{{ request.user }}</h1>
    <p class="lead">You failed in this exam with score of <b>{{ score }}</b></p>
    <hr class="my-4">
    
    <a class="btn btn-primary btn-lg" href="{% url 'exam:logout' %}" role="button">Log Out</a>
</div>

{% endif %}
{% endblock %}

exam/templates/exam/select_college.html
{% extends "exam/base.html" %}

{% block exam %}
<div class="jumbotron text-center">
    <h1 class="display-4">Welcome {{request.user}}</h1>
    <hr class="my-4">

    <form action="" method="post" class="form-group">
        {% csrf_token %}
        <select name="exam"  class="form-group">
            {% for exam in exams %}
            <option id={{exam.id}}>{{exam.exam_name}}</option>
                     
            {% endfor %}
        </select>
        
        <br><button type="submit" class="btn btn-primary my-2 ">Proceed</button>
    </form>
    
    
  </div>
{% endblock %}

exam/templates/exam/signin.html
{% extends 'exam/base.html' %}
{% block style %}
<style>
    body,
    html {
        margin: 0;
        padding: 0;
        height: 100%;
        background: #7abecc !important;
    }
    .user_card {
        width: 350px;
        margin-top: auto;
        margin-bottom: auto;
        background: #74cfbf;
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;

    }

    .form_container {
        margin-top: 20px;
    }

    #form-title{
        color: #fff;
        
    }

    .login_btn {
        width: 100%;
        background: #33ccff !important;
        color: white !important;
    }
    .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }
    .login_container {
        padding: 0 2rem;
    }
    .input-group-text {
        background: #f7ba5b !important;
        color: white !important;
        border: 0 !important;
        border-radius: 0.25rem 0 0 0.25rem !important;
    }
    .input_user,
    .input_pass:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }

    #messages{
        background-color: grey;
        color: #fff;
        padding: 10px;
        margin-top: 10px;
    }
</style>
{% endblock %}

{% block login %}
<a href="{% url 'adminapp:loginadmin' %}">Admin</a>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">


                <h3 id="form-title">LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                            <input type="password" name="password" placeholder="Password..." class="form-control" >
                    </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                             <input class="btn login_btn" type="submit" value="Login">
                           </div>
                </form>

            </div>
            {% for message in messages %}
                <p id="messages">{{ message }}</p>
            {% endfor %}
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="{% url 'exam:signup' %}" class="ml-2">Sign Up</a>
                </div>
                <div class="d-flex justify-content-center links">
                    Forgot Password? <a href="/reset_password" class="ml-2">Reset Password</a>
                </div>
        
            </div>
        </div>
    </div>
</div>
{% endblock %}