adminapp/urls.py
from django.urls import path
from . import views

app_name = 'adminapp'
urlpatterns = [
    path('', views.home, name="adminhome"),
    path('loginadmin/', views.loginAdmin, name="loginadmin"),
    path('logoutadmin/', views.logoutAdmin, name="logoutadmin"),

    path('college-student/<int:id>', views.fetchStudents, name="college-student"),
    path('all-students-data/', views.allStudents, name="all-students-data"),
    path('college-exam/<int:id>', views.fetchExams, name="college-exam"),
    path('exam/', views.exam, name="exam"),
    path('exam-info/<int:id>', views.examInfo, name="exam-info"),


    path('adminuser/', views.fetchAdmin, name="adminuser"),
    path('addcollege/', views.addCollege, name="addcollege"),
    path('addexam/', views.addExam, name="addexam"),
    path('addadmin/', views.addAdmin, name="addadmin"),
    path('addquestion/<int:id>', views.addQuestion, name="addquestion"),
    path('addoption/<int:id>', views.addOption, name="addoption"),
    path('edit-question/<int:exam_id>/<int:q_id>', views.editQuestion, name="edit-question"),
    path('studentrecords/<int:exam_id>/<int:college_id>', views.studentrecord, name="studentrecords"),
]

exam/urls.py
from django.urls import path
from . import views

app_name = 'exam'
urlpatterns = [
    path('', views.selectExam, name="select-exam"),
    path('home/<int:exam_id>', views.home, name='home'),
    path('signup/', views.register, name="signup"),
    path('signin/',views.signin, name="signin"),
    path('startexam/<int:id>', views.exam, name="startexam"),
    path('saveans/', views.saveans, name="saveans"),
    
    path('result/', views.result, name="result"),
    path('logout/', views.signout, name="logout"),
]

student_exam_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exam.urls', namespace='exam')),
    path('adminapp/', include('adminapp.urls' ,namespace="adminapp")),
]

adminapp/models.py
from django.db import models
from exam.models import College, Exam, Question, Option, Student
# Create your models here.

exam/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save



# Create your models here.
class College(models.Model):
    clg_name = models.CharField(max_length=300)

    def __str__(self):
        return self.clg_name

class Exam(models.Model):
    exam_name = models.CharField(max_length=100)
    college = models.ForeignKey(College, on_delete=models.CASCADE, related_name='exam')

    def __str__(self):
        return self.exam_name


class Question(models.Model):
    CATEGORY = (
        ('Aptitude', 'Aptitude'),
        ('Programming', 'Programming')
    )
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='exam')
    question_text = models.TextField()
    category = models.CharField(max_length=30, choices=CATEGORY, default="None")
    answer = models.CharField(max_length=1, null=True, blank=True)

    def __str__(self):
        return self.question_text

class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='question')
    option_value1 = models.CharField(max_length=1, default="A")
    option_text1 = models.CharField(max_length = 300)
    option_value2 = models.CharField(max_length=1,default="B")
    option_text2 = models.CharField(max_length = 300)
    option_value3 = models.CharField(max_length=1,default="C")
    option_text3 = models.CharField(max_length = 300)
    option_value4 = models.CharField(max_length=1,default="D")
    option_text4 = models.CharField(max_length = 300)

    def __str__(self):
        return self.question.question_text + " : " + self.option_text1 + ":" + self.option_text2 + ":" + self.option_text3 + ":" + self.option_text4



class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    college = models.ForeignKey(College, on_delete=models.CASCADE, related_name='college')
    roll_no = models.CharField(max_length=15)




def student_profile(sender, created, instance, **kwargs):
    if created:
        if instance.is_superuser == True:
            group = Group.objects.get(name='admin')
            instance.groups.add(group)
            print("True Again")

        else:
            group = Group.objects.get(name='student')
            instance.groups.add(group)
            Student.objects.create(
                user = instance, 
                college = instance.college,
                roll_no = instance.roll_no
            )   
post_save.connect(student_profile, sender=User)



class Record(models.Model):
    student_id = models.CharField(max_length=10)
    exam_id = models.CharField(max_length=10)
    question_id = models.CharField(max_length=10)
    answer = models.CharField(max_length=1, default='N')

    def __str__(self):
        return self.question_id + " : "+self.answer + "----Student_ID : " + self.student_id

adminapp/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse
from exam.models import College, Student, Exam, Question, Option, Record
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import AddCollegeForm, AddExamForm, CreateUserForm, QuestionForm, OptionForm
from django.contrib.auth import authenticate, login, logout
from exam.decorators import allowed_users, admin_only
from django.urls import reverse


# Create your views here.

def loginAdmin(request):
    auth_form = AuthenticationForm()
    if request.method == "POST":
        print(request.POST)
        user = authenticate(request, username = request.POST['username'], password=request.POST['password'])
        print(user)
        if user:
            login(request, user)
            return redirect(reverse('adminapp:adminhome'))

    context= {'auth_form':auth_form}
    return render(request, 'adminapp/admin_login.html', context)

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def logoutAdmin(request):
    logout(request)
    return redirect('/')

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def home(request):
    college_list = College.objects.all()
    college_count = college_list.count()
    student_count = Student.objects.all().count()
    exam_count = Exam.objects.all().count()

    context = {
        'college_list' : college_list,
        'college_count' : college_count,
        'student_count' : student_count,
        'exam_count' : exam_count
    }
    return render(request, 'adminapp/dashboard.html', context)

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def fetchStudents(request, id):
    students = Student.objects.filter(college=id).prefetch_related('college')
    context = {'students':students}
    return render(request, 'adminapp/studentlist.html', context)

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def allStudents(request):
    all_students = Student.objects.all()

    context = {'all_students':all_students}
    return render(request, 'adminapp/all_students.html', context)  

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def exam(request):
    college_list = College.objects.all()

    context = {'college_list':college_list}
    return render(request, 'adminapp/exam.html', context)

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def fetchExams(request, id):
    exam_list = Exam.objects.filter(college=id).prefetch_related('college')
    context = {'exam_list':exam_list}
    return render(request, 'adminapp/college_exam.html', context)

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def fetchAdmin(request):
    admin_users = User.objects.filter(is_staff=True)
    context = {'admin_users':admin_users}
    return render(request, 'adminapp/all_admin.html', context)

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def addCollege(request):
    college_form = AddCollegeForm()
    if request.method == "POST":
        college_form = AddCollegeForm(request.POST)
        if college_form.is_valid():
            college_form.save()
        return redirect(reverse('adminapp:adminhome'))
    context = {'form' : college_form}
    return render(request, 'adminapp/add_college.html', context)

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def addExam(request):
    exam_form = AddExamForm()
    if request.method == "POST":
        exam_form = AddExamForm(request.POST)
        if exam_form.is_valid():
            exam_form.save()
            return redirect(reverse('adminapp:exam'))
    context = {'exam_form' : exam_form}
    return render(request, 'adminapp/add_exam.html', context)

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def addAdmin(request):
    admin_form = CreateUserForm(initial={'is_staff':True, "is_superuser":True})
    if request.method == "POST":
        admin_form = CreateUserForm(request.POST)
        if admin_form.is_valid():
            print(True)
            admin_form.save()
            print('ok')
        return redirect(reverse('adminapp:adminuser'))
    context = {'admin_form':admin_form}
    return render(request, 'adminapp/create_admin.html', context)

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def examInfo(request, id):
    question_list = Question.objects.filter(exam=id).prefetch_related('exam')
    option_list = []
    for ques in question_list:
        try:
            option = Option.objects.get(question = ques.id)
            # print(type(options))
            # if len(options) > 1:    
            #     for option in options:
            #         if option.question.id == ques.id:
            #             option_list.append(option)
            # else:
            # option = options
            option_list.append(option)
        except:
            pass
        
    context = {'question_list':question_list, 'option_list':option_list, 'exam_id':id}
    return render(request, 'adminapp/exam_info.html', context)

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def addQuestion(request, id):
    exam = Exam.objects.get(id=id)
    question_form = QuestionForm(initial={'exam':exam})
    
    if request.method == 'POST':
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            question = question_form.cleaned_data['question_text']
            question_form.save()
            question = Question.objects.filter(question_text=question).reverse()[0]
            option_form = OptionForm(initial={'question' : question})
            context = {'option_form':option_form, 'exam_id':id}
            return render(request, 'adminapp/add_option.html', context)

    context = {'question_form':question_form}
    return render(request, 'adminapp/add_question.html', context)

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def addOption(request, id):
    if request.method == 'POST':
        option_form = OptionForm(request.POST)
        if option_form.is_valid():
            option_form.save()
        return redirect('adminapp:exam-info',id=id)
    else:
        return HttpResponse("It only can be seen after adding new questions")

@login_required(login_url='adminapp:loginadmin/')
@allowed_users(allowed_roles=['admin'])
def editQuestion(request, exam_id, q_id):
    question = Question.objects.get(id=q_id)
    option = Option.objects.get(question=q_id)
    
    question_form = QuestionForm(instance=question)
    option_form = OptionForm(instance=option)

    if request.method == "POST":
        question_form = QuestionForm(request.POST, instance=question) 
        option_form = OptionForm(request.POST, instance=option)
        if question_form.is_valid() and option_form.is_valid():
            question_form.save()
            option_form.save()
        return redirect('adminapp:exam-info', id=exam_id)
    context = {'question_form':question_form, 'option_form':option_form}
    return render(request, 'adminapp/update_question.html', context)

def studentrecord(request,exam_id, college_id):
    students = Student.objects.filter(college=college_id)
    exam = Exam.objects.get(id=exam_id)
    score_list = []
    for student in students:
        score = 0
        records = Record.objects.filter(exam_id=exam_id,student_id=student.user.id).exclude(answer='N')
        for record in records:
            question = Question.objects.get(id=record.question_id)
            if question.answer == record.answer:
                score += 2
        score_list.append(score)
    context={'students':students, 'score_list':score_list, 'exam':exam}
    return render(request, 'adminapp/studentrecord.html', context)

exam/views.py
from django.shortcuts import render, redirect, HttpResponsePermanentRedirect
from .models import College, Exam, Question, Option, Record
from django.core.paginator import Paginator
from .forms import CreateUserForm, StudentForm, UserAuthentication, ExamForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import allowed_users
from django.contrib import messages
from django.urls import reverse
import random


# Create your views here.
global question_list
global answer_list


def register(request):
    user_form = CreateUserForm()
    student_form = StudentForm()
    if request.method == "POST":
        user_form = CreateUserForm(request.POST)
        student_form = StudentForm(request.POST)
     
        if user_form.is_valid() and student_form.is_valid():
            try:
                username = user_form.cleaned_data['username']
                college = student_form.cleaned_data["college"]
                roll_no = student_form.cleaned_data.get("roll_no")
                user = user_form.save(commit=False)
                user.college = college
                user.roll_no = roll_no
                user.save()
                messages.success(request, f"{username} created successfully")
                return redirect(reverse('exam:signin'))
            except Exception as e:
                messages.warning(request, "Please Enter Valid/Unique(username, email)/Strong Data")

           
        else:
            messages.warning(request, "Please Enter Valid/Unique(username, email)/Strong Data")

    context ={'user_form':user_form,'student_form':student_form}
    return render(request, 'exam/register.html', context)

def signin(request):
    auth_form = UserAuthentication()
    if request.method == "POST":
        user = authenticate(request, username = request.POST['username'], password=request.POST['password'])
        if user:
            login(request, user)
            return redirect('/')
        else:
            messages.warning(request, "Invalid Credentials")

    context= {'auth_form':auth_form}
    return render(request, template_name='exam/signin.html', context = context)


@login_required
@allowed_users(allowed_roles=['student'])
def signout(request):
    logout(request)
    return redirect('/')

@login_required(login_url='exam:signin')
@allowed_users(allowed_roles=['student'])
def selectExam(request):
    exams = Exam.objects.filter(college = request.user.student.college.id)
    if request.method == "POST":
        exam = request.POST['exam']
        exam = Exam.objects.filter(exam_name=exam, college=request.user.student.college.id)
        return redirect(reverse('exam:home',kwargs={'exam_id' : exam[0].id}))
    context = {'exams':exams}
    return render(request, 'exam/select_college.html', context)


@login_required(login_url='exam:signin')
@allowed_users(allowed_roles=['student'])
def home(request, exam_id):
    question = Question.objects.filter(exam=exam_id)
    global answer_list
    answer_list = []
    global question_list
    question_list = list(question)
    for question in question_list:
        Record.objects.create(student_id=request.user.id, exam_id=exam_id, question_id=question.id)
    random.shuffle(question_list)
    return render(request, 'exam/home.html', {'exam_id':exam_id})

@login_required(login_url='exam:signin')
@allowed_users(allowed_roles=['student'])
def exam(request, id):
    global question_list
    exam_question = question_list[:]
    option_list = []
    for ques in exam_question:
        option = Option.objects.get(question=ques.id)
        option_list.append(option)

    context = {'questions': exam_question, 'questions_page': exam_question, 'option_list': option_list, 'exam_id':id}
    return render(request, 'exam/exam.html', context)

@login_required
def saveans(request):
    question_id = request.GET['qid']
    answer = request.GET['ans']
    exam_id = request.GET['eid']
    Record.objects.filter(question_id=question_id, exam_id=exam_id, student_id=request.user.id).update(answer=answer)
    

@login_required(login_url='exam:signin')
@allowed_users(allowed_roles=['student'])
def result(request):
    score = 0
    global question_list
    compare_list = question_list[:]
    for question in compare_list:
        record = Record.objects.get(question_id=question.id)

        if record.answer == question.answer:
            score += 2
    return render(request, 'exam/result.html', {'score':score})

adminapp/templates/adminapp/add_college.html
{% extends "adminapp/main.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="exists"></div>
<form action="" method="post">
    {% csrf_token %}
    {{form|crispy}}
    

   <button class="btn btn-info" type="submit">Add College</button>
</form>


{% block scripts %}
    <script>
        $.ajax({
            
        })
    </script>
{% endblock scripts %}
    
{% endblock %}

adminapp/templates/adminapp/add_option.html
{% extends "adminapp/main.html" %}
{% load crispy_forms_tags %}



{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-md-5  shadow-lg bg-white rounded">

                <form action="{% url 'adminapp:addoption' exam_id%}" method="post" class="form-group text-center">
                    {% csrf_token %}
                    {{option_form|crispy}}
                  
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock  %}
    

adminapp/templates/adminapp/all_admin.html
{% extends "adminapp/main.html" %}


{% block content %}
<div class="container">
    <div class="colleges col-md-10 my-4 offset-md-1 shadow-lg bg-white rounded align-middle"><h3 class="head text-center text-muted align-middle">Admins<span class="mx-3"><a href="{% url 'adminapp:addadmin' %}" class="btn btn-success">Add Admin</a></span></h3></div>
    <table class="table table-striped">
        <thead>

          <tr>
            <th scope="col">#</th>
            <th scope="col">User Name</th>
            <th scope="col">Email</th>
            <th scope="col">Is SuperUser</th>
            <th scope="col">Is Staff</th>
            <th></th>
            
          </tr>
        </thead>
        <tbody>
            
            {% if admin_users %}
            {% for admin in admin_users %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{admin.username}}</td>
                    <td>{{admin.email}}</td>
                    <td>{{admin.is_superuser}}</td>
                    <td>{{admin.is_staff}}</td>

                </tr>
            {% endfor %}
                
            {% else %}
            <tr>
                <th scope="row">#</th>
                <td>#</td>
                <td>#</td>
                <td>#</td>
                <td>#</td>
            </tr>
            {% endif %}


                
        </tbody>
      </table>
  </div>
{% endblock %}

adminapp/templates/adminapp/college_exam.html
{% extends 'adminapp/main.html' %}

{% block style %}
<style>

  .hover{
    min-height: 4em;
    text-decoration: none;
    outline: none;
    text-align: center;
    align-items: center;
    color:black;
  }
  .hover:hover{
    text-decoration: none;
    background-color: black !important;
    color: white !important;
  }
  .hover a:hover{
    color: white;
    text-decoration: none;
  }
  .hover a{
    text-decoration: none;
  }
  
  
</style>
{% endblock style %}

{% block content %}
<div class="container">
    <div class="colleges col-md-10 my-4 offset-md-1 shadow-lg bg-white rounded align-middle"><h3 class="head text-center text-muted align-middle">Exam</h3></div>
    <table class="table table-striped">
        <thead>

          <tr>
            <th scope="col">#</th>
            <th scope="col">Exam</th>
            <th scope="col">College</th>
            <th>View</th>
            
          </tr>
        </thead>
        <tbody>
            
            {% if exam_list %}
            {% for exam in exam_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{exam.exam_name}}</td>
                    
                    <td>{{exam.college}}</td>
                    <td><a href="{% url 'adminapp:exam-info' exam.id%}" class="btn btn-sm btn-outline-dark">View</a></td>
                    
                </tr>
            {% endfor %}
                
            {% else %}
            <tr>
                <th scope="row">#</th>
                <td>#</td>
                <td>#</td>
                <td>#</td>
                <td>#</td>
            </tr>
            {% endif %}


                
        </tbody>
      </table>
  </div>
<hr class="my-4">
  <div class="colleges col-md-10 offset-md-1 shadow-lg bg-white rounded align-middle"><h3 class="head text-center text-muted align-middle">Select Exam to See Student Records</h3></div>
<div class="container">
		
	<!-- <div class="hover col-md-5 offset-md-1 mt-2 shadow-lg p-3 bg-white rounded"> -->
    <div class="row mt-3">
    {% for exam in exam_list %}
		<a href="{% url 'adminapp:studentrecords' exam_id=exam.id college_id=exam.college.id %}" class="btn btn-primary hover col-md-5 offset-md-1 mt-2 shadow-lg p-3 bg-white rounded">	
      {{ exam }}  
		</a>
    {% endfor %}
	</div>
		
	
	</div>
</div>

{% endblock  %}

adminapp/templates/adminapp/create_admin.html
{% extends 'adminapp/main.html' %}
{% load crispy_forms_tags %}
{% block style %}
  <style>
    .container{
        max-width: 43em;
    }
  </style>
{% endblock style %}

{% block content %}
<div class="container text-center align-middle my-5">

    <form action="" method="post" class="bootstrap4">
        {% csrf_token %}
        {{admin_form|crispy}}
        <!-- {% for form in admin_form %}
        {{form.label}}:{{form}}<br> -->
        <!-- {% endfor %} -->
        <button type="submit" class="btn btn-info">Create Admin</button>
    </form>
</div>
  
{% endblock  %}

adminapp/templates/adminapp/dashboard.html
{%  extends 'adminapp/main.html' %}

{% block content %}

{%  include 'adminapp/status.html' %}
{% block style %}
<style>
	#img{
		height: 47px;
		width: 47px;
	}
	.hover{
		min-height: 4em;
		text-decoration: none;
		outline: none;
		text-align: center;
		align-items: center;
		color:black;
	}
	.hover:hover{
		text-decoration: none;
		background-color: black !important;
		color: white !important;
	}
	.hover a:hover{
		color: white;
		text-decoration: none;
	}
	.hover a{
		text-decoration: none;
	}
	.colleges{
		min-height: 2.5em;
	}
	.head{
		line-height: 2.5em;
	}
	
</style>
{% endblock %}
<br>
<hr class="my-5">
<div class="colleges col-md-10 offset-md-1 shadow-lg bg-white rounded align-middle"><h3 class="head text-center text-muted align-middle">Colleges<span class="mx-3"><a href="{% url 'adminapp:addcollege' %}" class="btn btn-success">Add College</a></span></h3></div>
<div class="container">
	<div class="row mt-3">
	{% for college in college_list %}
		
		
	<!-- <div class="hover col-md-5 offset-md-1 mt-2 shadow-lg p-3 bg-white rounded"> -->

		<a href="{% url 'adminapp:college-student' college.id %}" class="btn btn-primary hover col-md-5 offset-md-1 mt-2 shadow-lg p-3 bg-white rounded">	
			<div>{{college}} </div>
				
		</a>
	<!-- </div> -->
		
	
	{% endfor %}
	
	</div>
</div>
<br>
<hr class="my-4 bold">

{% endblock %}

adminapp/templates/adminapp/exam_info.html
{% extends "adminapp/main.html" %}

{% block content %}
<div class="container-fluid">
    <div class="colleges col-md-10 my-4 offset-md-1 shadow-lg bg-white rounded align-middle"><h3 class="head text-center text-muted align-middle">Questions<span class="mx-3"><a href="{% url 'adminapp:addquestion' exam_id %}" class="btn btn-success">Add question</a></span></h3></div>
    <table class="table table-striped">
        <thead>
            
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col" class="text-center">Question</th>
                <th scope="col" class="text-center">Op1</th>
                <th scope="col" class="text-center">Op2</th>
                <th scope="col" class="text-center">Op3</th>
                <th scope="col" class="text-center">Op4</th>
                <th scope="col" class="text-center">Answer</th>
                <th>Edit</th>
                
            </tr>
        </thead>
        <tbody>
            
        
            {% for question in question_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{question}}</td>
                        {% for option in option_list %}
                          
                          {% if option.question.id == question.id %}
                          <td class="text-center">{{option.option_text1}}</td>
                          <td class="text-center">{{option.option_text2}}</td>
                          <td class="text-center">{{option.option_text3}}</td>
                          <td class="text-center">{{option.option_text4}}</td>
                          <td class="text-center">{{question.answer}}</td>
                          <td class="text-center"><a href="{% url 'adminapp:edit-question' exam_id=exam_id q_id=question.id %}" class="btn btn-sm btn-outline-dark">Edit</a></td>
                              
                              
                          {% endif %}
                              
                          
                          
                          {% endfor %}
                        </tr>
                {% endfor %}
                    
    
    
                    
            </tbody>
          </table>
      </div>

{% endblock %}

adminapp/templates/adminapp/main.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Admin App</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/main.css' %}" >
	<script
  src="https://code.jquery.com/jquery-3.5.1.js"
  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
  crossorigin="anonymous"></script>
	{% block style %}

	{% endblock %}
</head>
<body>
	{%  include 'adminapp/navbar.html' %}
	<div class="container-fluid">
	{% block content %}



	{% endblock %}
    </div>
	
</body>

{% block scripts %}
	
{% endblock scripts %}
	

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

adminapp/templates/adminapp/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'adminapp:adminhome' %}">Eligility Portal
    <div class="text-muted"><small>Custom Dashboard</small></div>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% comment %} {% if request.user.is_staff %} {% endcomment %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'adminapp:adminhome' %}">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'adminapp:all-students-data' %}">Students</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'adminapp:exam' %}">Exam</a>
      </li>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'adminapp:adminuser' %}">Admin</a>
      </li>
    </ul>
  </div>

    <style>
      #user-mg, #link-nav{
        color:#fff;
        margin-right: 3px;
      }
    </style>
  <span id="user-mg">Hello,{{request.user}}</span>
  <span><a href="{% url 'adminapp:logoutadmin' %}" class="nav-link link-nav">Logout</a></span>
</nav>

adminapp/templates/adminapp/update_question.html
{% extends "adminapp/main.html" %}


{% block style %}
  <style>
      #id_question{
          max-width:280px;
      }
  </style>
{% endblock %}

{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-md-5  shadow-lg bg-white rounded">

                <form action=" " method="post" class="form-group text-center">
                    {% csrf_token %}
                    {% for field in question_form.visible_fields %}
                    <div class="form-group">
                        {{ field.label_tag }}:
                        {{ field }}
                      </div>
                    {% endfor %}
                    <hr>
                    {% for option in  option_form.visible_fields%}
                    
                    <div class="form-group">

                        {{option.label_tag}}
                        {{option}}
                    </div>
                    
                    {% endfor %}
                  
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock  %}
    